### ISSUE TITLE
Tests don't match deliverables for Rails Mock Challenge - Camping Fun

### ISSUE THREAD

**Issue by karen-olson** [learn-co-curriculum/phase-4-mock-challenge-camping-fun#4]
### Canvas Link

https://learning.flatironschool.com/courses/4324/assignments/127833?module_item_id=264353

### Concern

The rspec tests do not cover all of the deliverables listed in the mock code challenge lesson.

**Comment by ihollander** [comment]
Hi @karen-olson, I a look at the tests for this and as far as I could tell, the tests appear to cover all the deliverables. I took a look at your fork of this assignment and it appears that some of the tests were deleted as you were working on the assignment:

https://github.com/karen-olson/phase-4-mock-challenge-camping-fun/commit/7f92c023e36bf39e6d5818df35f39eb4e0f7008d

This can happen when you use the `rails d` command without the `--no-test-framework` flag to remove the files created by a `rails g` command. For example, running `rails d resource camper` would delete the test files for the `Camper` model and the requests.

I'll close this issue, but if you believe there's still a problem with the source code, please feel free to re-open it!

**Comment by karen-olson** [comment]
Thank you - that's exactly what happened - I used rails d without
--no-test-framework. Thanks for clearing that up!
